# Generated by Django 6.0 on 2026-01-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CITIZEN_COMPLAIN', '0005_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='is_seen_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
