# Generated by Django 6.0 on 2026-01-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CITIZEN_COMPLAIN', '0006_contactmessage_is_seen_by_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='admin_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
