# Generated by Django 6.0 on 2026-01-11 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CITIZEN_COMPLAIN', '0007_contactmessage_admin_feedback_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='admin_feedback',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='location',
        ),
        migrations.AddField(
            model_name='complaint',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='complaint_images/'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('Economy', 'Economy'), ('Social', 'Social'), ('Politics', 'Politics')], max_length=20),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CITIZEN_COMPLAIN.registereduser'),
        ),
    ]
